"""
cstopo3.fast01 -- b0 and b1 of a Dowker complex, at 3+1D scale.

Why a special path is needed.  For a point cloud sampling a 3-manifold, the
Dowker/clique complex reconstructs the topology only when the cover balls have
radius r ~ 2 x the mean landmark spacing s, and the facet size is then
m = (4pi/3)(r/s)^3 ~ 25-40 REGARDLESS of the sampling density.  So cap ~ 30 is
forced by the dimension, and C(30,3) = 4060 triangles per facet makes the
generic homology path (materialising every simplex as a tuple) hopeless.

The observation that rescues it: over Z2, the class of the boundary of a
triangle in the cycle space of the 1-skeleton, expressed in the fundamental
basis of a spanning forest, is simply the set of NON-TREE edges among its three
edges.  Every column of d_2 therefore has at most three nonzeros in a space of
dimension m = n_1 - n_0 + b_0, and the rank computation is cheap.  The number
of triangles can be large; the space they live in is small.

    b_0 = components of the 1-skeleton                       (union-find)
    b_1 = m - rank(d_2 in cycle-space coordinates)

For a closed orientable 3-manifold b_2 = b_1 by Poincare duality, so b_1 alone
distinguishes S^3 (0) from S^1 x S^2 (1); b_2 is a check on manifoldness and is
computed separately, with a size guard, by z2.betti.
"""
from __future__ import annotations
import numpy as np
from math import comb

__all__ = ["betti01", "skeleton", "n_triangles_estimate"]

_TRIPLE_CACHE = {}
_PAIR_CACHE = {}


def _triples(m):
    if m not in _TRIPLE_CACHE:
        idx = np.array([(i, j, k) for i in range(m) for j in range(i + 1, m)
                        for k in range(j + 1, m)], dtype=np.int32)
        _TRIPLE_CACHE[m] = idx.reshape(-1, 3)
    return _TRIPLE_CACHE[m]


def _pairs(m):
    if m not in _PAIR_CACHE:
        idx = np.array([(i, j) for i in range(m) for j in range(i + 1, m)],
                       dtype=np.int32)
        _PAIR_CACHE[m] = idx.reshape(-1, 2)
    return _PAIR_CACHE[m]


def n_triangles_estimate(facets):
    return int(sum(comb(len(f), 3) for f in facets if len(f) >= 3))


# ======================================================================
#  1-skeleton
# ======================================================================
def skeleton(facets, nv):
    """Distinct edges of the complex, as an (n_edges, 2) int32 array."""
    codes = []
    for f in facets:
        m = len(f)
        if m < 2:
            continue
        a = np.asarray(f, dtype=np.int64)
        pr = _pairs(m)
        e = a[pr]
        codes.append(e[:, 0] * nv + e[:, 1])
    if not codes:
        return np.zeros((0, 2), dtype=np.int32)
    c = np.unique(np.concatenate(codes))
    return np.column_stack([c // nv, c % nv]).astype(np.int32)


def _components(edges, verts):
    """Union-find over the given vertex labels."""
    parent = {int(v): int(v) for v in verts}

    def find(a):
        r = a
        while parent[r] != r:
            r = parent[r]
        while parent[a] != r:
            parent[a], a = r, parent[a]
        return r

    tree = np.zeros(len(edges), dtype=bool)
    for n, (u, v) in enumerate(edges):
        ru, rv = find(int(u)), find(int(v))
        if ru != rv:
            parent[ru] = rv
            tree[n] = True
    roots = {find(int(v)) for v in verts}
    return len(roots), tree


# ======================================================================
#  b0, b1
# ======================================================================
def betti01(facets, nv, max_triangles=None, shuffle_seed=0, verbose=False):
    """(b0, b1) of the complex generated by `facets` on vertex labels < nv.

    Isolated vertices (appearing in no facet) are ignored: only the covered
    subcomplex is measured, and coverage is reported by the caller.
    """
    verts = sorted({int(v) for f in facets for v in f})
    if not verts:
        return (0, 0), {}
    edges = skeleton(facets, nv)
    n0, n1 = len(verts), len(edges)
    b0, tree = _components(edges, verts)
    m = n1 - n0 + b0                       # cycle-space dimension
    info = dict(n_verts=n0, n_edges=n1, cycle_dim=m, b0=b0)
    if m == 0:
        info["rank_d2"] = 0
        return (b0, 0), info

    # cycle index for every edge: -1 for tree edges, else 0..m-1
    cyc = np.full(nv * nv, -1, dtype=np.int32) if nv * nv <= 40_000_000 else None
    if cyc is None:
        raise MemoryError(f"|L|={nv} too large for the dense edge table; "
                          "subsample the antichain further")
    nont = np.flatnonzero(~tree)
    codes = edges[:, 0].astype(np.int64) * nv + edges[:, 1]
    cyc[codes[nont]] = np.arange(nont.size, dtype=np.int32)

    # ---- distinct triangles, deduped with numpy in chunks ----
    chunks, buf, nbuf = [], [], 0
    for f in facets:
        mm = len(f)
        if mm < 3:
            continue
        a = np.asarray(sorted(f), dtype=np.int64)
        tr = a[_triples(mm)]
        buf.append((tr[:, 0] * nv + tr[:, 1]) * nv + tr[:, 2])
        nbuf += buf[-1].size
        if nbuf > 4_000_000:
            chunks.append(np.unique(np.concatenate(buf))); buf, nbuf = [], 0
    if buf:
        chunks.append(np.unique(np.concatenate(buf)))
    if not chunks:
        info["rank_d2"] = 0
        return (b0, m), info
    tri = np.unique(np.concatenate(chunks))
    info["n_triangles"] = int(tri.size)

    k3 = tri // nv
    i0, i1, i2 = k3 // nv, k3 % nv, tri % nv
    E = np.column_stack([cyc[i0 * nv + i1], cyc[i0 * nv + i2], cyc[i1 * nv + i2]])

    # ---- Z2 rank of a matrix with <= 3 nonzeros per column ----
    # Python ints are the right bitset here: for m ~ 10^4 a column is ~1 kB and
    # a bigint XOR is a single C loop, an order of magnitude cheaper than the
    # per-call overhead of a numpy uint64 array of the same length.
    piv = {}
    rank = 0
    order = np.arange(tri.size)
    if shuffle_seed is not None:
        np.random.default_rng(shuffle_seed).shuffle(order)
    Elist = E[order].tolist()
    for row in Elist:
        v = 0
        for r in row:
            if r >= 0:
                v ^= 1 << r
        while v:
            low = (v & -v).bit_length() - 1
            p = piv.get(low)
            if p is None:
                piv[low] = v
                rank += 1
                break
            v ^= p
        if rank == m:
            break
    info.update(rank_d2=rank, b1=m - rank)
    if verbose:
        print(f"      b0={b0} n0={n0} n1={n1} cycdim={m} rank={rank} "
              f"tri={info.get(chr(34)+chr(34)) or info.get('n_triangles')} -> b1={m-rank}")
    return (b0, m - rank), info
