"""
cstopo3.z2 -- Z2 homology of a simplicial complex given by its facets.

Designed for the 3+1D problem, where the discriminating observable requires
H_1 and H_2 rather than H_1 alone, and the complex is therefore an order of
magnitude larger than in the 2+1D case.  Three things make it tractable:

  1. Dowker duality.  The nerve of the shadow cover {sigma(y)} and the complex
     on the antichain whose facets are the sigma(y) have isomorphic homology
     (Dowker 1952).  We always build the latter: its vertex set is the
     antichain (~10^3-10^4 elements) rather than the witness set, and every
     facet has at most `cap` vertices by construction, so face enumeration is
     bounded by n_facets * C(cap, k+1) instead of being combinatorial in |A|.

  2. Truncation.  H_k of a complex depends only on simplices of dimension
     <= k+1, so for Betti numbers up to maxdim we build only up to maxdim+1.

  3. Elementary collapse.  Removing free pairs (a simplex with exactly one
     coface, together with that coface) preserves homotopy type exactly.  On
     dense samples of a 3-manifold this removes the large majority of
     simplices before any linear algebra is attempted.

Only numpy is required.
"""
from __future__ import annotations
import numpy as np
from itertools import combinations

__all__ = ["faces_by_dim", "collapse", "z2_rank", "betti", "betti_report"]


# ======================================================================
#  face enumeration
# ======================================================================
def faces_by_dim(facets, maxdim):
    """All faces of dimension 0..maxdim of the complex generated by `facets`.

    Returns {d: sorted list of vertex tuples}.  Facets are arbitrary iterables
    of hashable vertex labels; duplicates and non-maximal facets are harmless.
    """
    out = {d: set() for d in range(maxdim + 1)}
    for f in facets:
        s = tuple(sorted(set(f)))
        for k in range(1, min(len(s), maxdim + 1) + 1):
            out[k - 1].update(combinations(s, k))
    return {d: sorted(v) for d, v in out.items() if v}


# ======================================================================
#  elementary collapse
# ======================================================================
def collapse(faces, verbose=False):
    """Iterated elementary collapse.  Exact: preserves homotopy type.

    `faces` is {d: list of tuples} as returned by faces_by_dim.  Returns a new
    dict in the same format.  A free face is a simplex with exactly one coface;
    it is removed together with that coface.
    """
    alive = {d: set(v) for d, v in faces.items()}
    maxd = max(alive)

    # coface bookkeeping: for each simplex, the set of its cofaces one dim up
    cof = {}
    for d in range(1, maxd + 1):
        for t in alive.get(d, ()):
            for i in range(len(t)):
                cof.setdefault(t[:i] + t[i + 1:], set()).add(t)

    def nfree(s):
        return len(cof.get(s, ()))

    queue = [s for d in range(maxd) for s in alive.get(d, ()) if nfree(s) == 1]
    removed = 0
    while queue:
        s = queue.pop()
        c = cof.get(s)
        if not c or len(c) != 1:
            continue
        t = next(iter(c))
        ds, dt = len(s) - 1, len(t) - 1
        if s not in alive.get(ds, ()) or t not in alive.get(dt, ()):
            continue
        alive[ds].discard(s)
        alive[dt].discard(t)
        removed += 2
        # t disappears as a coface of all its facets
        for i in range(len(t)):
            f = t[:i] + t[i + 1:]
            cc = cof.get(f)
            if cc is not None:
                cc.discard(t)
                if len(cc) == 1 and f in alive.get(len(f) - 1, ()):
                    queue.append(f)
        # s disappears as a coface of all its facets
        for i in range(len(s)):
            f = s[:i] + s[i + 1:]
            cc = cof.get(f)
            if cc is not None:
                cc.discard(s)
                if len(cc) == 1 and f in alive.get(len(f) - 1, ()):
                    queue.append(f)
        cof.pop(s, None)
        cof.pop(t, None)
    out = {d: sorted(v) for d, v in alive.items() if v}
    if verbose:
        before = sum(len(v) for v in faces.values())
        after = sum(len(v) for v in out.values())
        print(f"    collapse: {before} -> {after} simplices "
              f"({removed} removed, factor {before/max(after,1):.1f})")
    return out


# ======================================================================
#  Z2 rank, bit-packed
# ======================================================================
def z2_rank(cols, nrows):
    """Rank over Z2 of a matrix given as a list of row-index arrays (columns).

    Columns are bit-packed into uint64 words and reduced with a pivot table
    keyed on the lowest set bit, as in the standard persistence reduction.
    """
    if not cols or nrows == 0:
        return 0
    W = (nrows + 63) // 64
    piv = {}                      # low row index -> packed column
    rank = 0
    for rows in cols:
        if len(rows) == 0:
            continue
        v = np.zeros(W, dtype=np.uint64)
        r = np.asarray(rows, dtype=np.int64)
        np.bitwise_xor.at(v, r >> 6, np.uint64(1) << (r & 63).astype(np.uint64))
        while True:
            nz = np.flatnonzero(v)
            if nz.size == 0:
                break                                  # column died: dependent
            w = int(nz[0])
            word = int(v[w])
            low = (w << 6) + ((word & -word).bit_length() - 1)
            p = piv.get(low)
            if p is None:
                piv[low] = v
                rank += 1
                break
            v = v ^ p
    return rank


# ======================================================================
#  Betti numbers
# ======================================================================
def betti(facets, maxdim=2, do_collapse=True, verbose=False):
    """Betti numbers b_0..b_maxdim over Z2 of the complex generated by facets.

    The complex is built to dimension maxdim+1, which is exactly what H_maxdim
    depends on.
    """
    faces = faces_by_dim(facets, maxdim + 1)
    if verbose:
        print("    raw faces:", {d: len(v) for d, v in sorted(faces.items())})
    if do_collapse:
        faces = collapse(faces, verbose=verbose)
        if verbose:
            print("    after collapse:", {d: len(v) for d, v in sorted(faces.items())})

    idx = {d: {s: i for i, s in enumerate(v)} for d, v in faces.items()}
    n = {d: len(v) for d, v in faces.items()}
    rank = {}
    for d in range(1, maxdim + 2):
        if d not in faces or (d - 1) not in faces:
            rank[d] = 0
            continue
        below = idx[d - 1]
        cols = []
        for s in faces[d]:
            rows = [below[s[:i] + s[i + 1:]] for i in range(len(s))
                    if (s[:i] + s[i + 1:]) in below]
            cols.append(rows)
        rank[d] = z2_rank(cols, n[d - 1])
    return tuple(n.get(d, 0) - rank.get(d, 0) - rank.get(d + 1, 0)
                 for d in range(maxdim + 1))


def betti_report(facets, maxdim=2, **kw):
    """betti() plus size diagnostics, for scaling studies."""
    import time
    t0 = time.time()
    faces = faces_by_dim(facets, maxdim + 1)
    raw = {d: len(v) for d, v in sorted(faces.items())}
    t_faces = time.time() - t0
    t0 = time.time()
    red = collapse(faces)
    t_coll = time.time() - t0
    small = {d: len(v) for d, v in sorted(red.items())}
    t0 = time.time()
    b = betti(facets, maxdim=maxdim, do_collapse=True, **kw)
    t_tot = time.time() - t0
    return dict(betti=b, raw=raw, collapsed=small,
                raw_total=sum(raw.values()), collapsed_total=sum(small.values()),
                t_faces=t_faces, t_collapse=t_coll, t_total=t_tot,
                max_facet=max((len(f) for f in facets), default=0))
