import sympy as sp

print("="*74)
print("A. Q2 ALTERNATIVE: derive Leff with NO variation, from N-linearity alone")
print("="*74)
Lam,dchidV = sp.symbols('Lambda c', real=True)
alpha,G,ell,N = sp.symbols('alpha G ell N', positive=True)
# Continuum Lambda-term in the action:  S_Lam = -(1/16 pi G) * 2 Lam * V,  V = ell^4 N
S_Lam = -(1/(16*sp.pi*G))*2*Lam*(ell**4*N)
# GB term: S_GB = (alpha/2kappa^2) * 32 pi^2 chi, kappa^2 = 8 pi G,
#          chi = chi_bg + (dchi/dV) * V   -> the N-linear piece:
S_GB  = (alpha/(2*(8*sp.pi*G)))*32*sp.pi**2*(dchidV*ell**4*N)
sol = sp.solve(sp.Eq(S_Lam, S_GB), Lam)
print("  Matching the two terms LINEAR IN N:")
print("    S_Lambda =", sp.simplify(S_Lam))
print("    S_GB     =", sp.simplify(S_GB))
print("    =>  Lambda_eff =", sp.simplify(sol[0]), "   [paper: -16 pi^2 alpha dchi/dV]")
print("  Identical. No functional derivative, no Lanczos-Lovelock, no cell decomposition.")

print()
print("="*74)
print("B. Q2 SCALE AMBIGUITY: what is held fixed under the variation?")
print("="*74)
print("  chi_defects = (sum_i dchi_i n_i) * V,  and in CST  V = ell^4 N,  n ~ ell^-4 * nbar")
print("  => chi_defects = (sum dchi_i nbar_i) * N          <- depends ONLY on N")
print()
print("  (i) ell fixed (discreteness scale a constant of nature):")
print("      dV != 0  =>  dN != 0  =>  d(chi) != 0   =>  Lambda_eff = -16 pi^2 alpha dchi/dV   [paper]")
print("  (ii) N fixed (the causal set is THE object; varying g rescales ell):")
print("      dV != 0  =>  d(ell^4) = dV/N  =>  n -> n (V/V')  =>  nV = N invariant")
print("      =>  d(chi) = 0  =>  Lambda_eff = 0")
print("  The paper never states which. The result exists only under (i).")

print()
print("="*74)
print("C. Q2 ERROR: chi is NOT additive over a cell decomposition")
print("="*74)
print("  Sec IV.D writes  int_Omega sqrt(g) G = 32pi^2 sum_a chi(C_a) - int_dOmega Q,")
print("  claiming internal boundary terms cancel pairwise.  If they did, comparing with")
print("  the same identity applied to Omega directly would give chi(Omega) = sum_a chi(C_a).")
print()
print("  Counterexample: cut a 4-ball into two 4-balls along a 3-ball.")
print("    chi(B^4) = 1 ;  sum over cells = 1 + 1 = 2 ;  inclusion-exclusion:")
print("    chi(A u B) = chi(A)+chi(B)-chi(A n B) = 1 + 1 - 1 = 1   (A n B = B^3, chi=1)")
print("  => sum_a chi(C_a) OVERCOUNTS by chi(internal faces).  The Chern-Gauss-Bonnet")
print("     boundary term for a region WITH CORNERS carries corner contributions that do")
print("     not cancel; that mismatch IS the failure of additivity.")
print()
print("  The DEFECT COUNT, by contrast, is exactly additive (it counts point events).")
print("  So Eq.(18) alone -- chi = chi_bg + sum_i dchi_i -- gives the result cleanly.")
print("  The cell decomposition is both wrong and unnecessary; delete it.")

print()
print("="*74)
print("D. Q1: mean vs variance of the SAME Poisson process")
print("="*74)
V,n,dchi = sp.symbols('V n delta_chi', positive=True)
mean = dchi*n*V           # sum of dchi_i over the region
var  = dchi**2*n*V
print("  defect count in V:  Poisson,  <N_def> = Var = n V")
print("  topological charge: <sum dchi_i> =", mean, "    sigma =", sp.sqrt(var))
print()
print("  => Lambda_mean  ~ alpha * dchi * n            (CONSTANT)      -> this paper, w = -1")
print("  => sigma_Lambda ~ alpha * dchi * sqrt(n/V) ~ H^2  (V ~ H^-4) -> everpresent Lambda")
print()
print("  They are the FIRST and SECOND moments of one process.  Everpresent Lambda sets the")
print("  first moment to zero by assuming the two topology-change species cancel in the mean.")
print("  The Nariai result says they do not cancel -- only one species is supported.")
print("  THAT is the novelty, and it is a one-line statement.")
